== 계정

=== 계정 생성

새로운 계정을 생성할 수 있습니다.

operation::sign-up[snippets='http-request,request-headers,request-parts,request-part-request-fields,http-response,response-headers,response-fields']

=== 로그인

생성된 계정을 통해 로그인할 수 있습니다.

==== HTTP 요청 예시
[source,http,options="nowrap"]
----
POST /login HTTP/1.1
Content-Type: application/json;charset=UTF-8
Content-Length: 42
X-CSRF-TOKEN: 07d17f92-72e0-4f4a-a84e-6acc75c121c2
Host: localhost:8080

{
  "email" : "test1@naver.com",
  "password": "test1"
}
----

==== 요청 헤더
|===
|Name|Description

|`+Content-Type+`
|application/json

|===

==== 요청 필드
|===
|Path|Type|Description

|`+email+`
|`+String+`
|로그인 아이디(이메일)
|`+password+`
|`+String+`
|비밀번호

|===

==== HTTP 응답 예시
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 260

{
    "token": {
        "accessToken": "bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MTlAbmF2ZXIuY29tIiwicm9sZXMiOlsiUk9MRV9BQ0NPVU5UIl0sImV4cCI6MTY1OTQzMDgyN30.wCPbVRmiNsEPUATd56v_Ge6UnzH84wxABDXmWH7SlU4",
        "expirationTime": "2022-08-02T09:00:27.945+00:00"
    },
    "account": {
        "id": 23,
        "image": "https://masiottae-image-bucket.s3.ap-northeast-2.amazonaws.com/account/502c53ae-774a-44b6-9494-a9645a12fb73.png",
        "nickName": "test19",
        "email": "test19@naver.com",
        "snsAccount": "test sns",
        "createdAt": "2022-08-02T16:18:37.871067",
        "menuCount": 0
    }
}
----

==== 응답 헤더
|===
|Name|Description

|`+Content-Type+`
|application/json

|===

==== 응답 필드
|===
|Path|Type|Description

|`+token.accessToken+`
|`+String+`
|토큰 값
|`+token.expirationTime+`
|`+String+`
|토큰 만료 기간
|`+account.id+`
|`+String+`
|식별자
|`+account.image+`
|`+String+`
|프로필 이미지 url
|`+account.nickName+`
|`+String+`
|닉네임
|`+account.email+`
|`+String+`
|이메일
|`+account.snsAccount+`
|`+String+`
|SNS 계정
|`+account.createdAt+`
|`+String+`
|가입 일자
|`+account.menuCount+`
|`+String+`
|보유 메뉴 개수
|===



=== 계정 삭제

하나의 계정을 삭제할 수 있습니다.

operation::delete-one-account[snippets='http-request,path-parameters']

=== 계정 전체 조회

저장된 모든 계정 정보를 조회할 수 있습니다.

operation::find-all-accounts(paging)[snippets='http-request,request-headers,request-parameters,http-response,response-headers,response-fields']

=== 계정 단건 조회

저장된 하나의 계정 정보를 조회할 수 있습니다.

operation::find-one-account[snippets='http-request,request-headers,path-parameters,http-response,response-headers,response-fields']

=== 비밀번호 변경

저장된 하나의 계정 비밀번호를 변경할 수 있습니다.

operation::update-password[snippets='http-request,request-headers,request-headers']

=== 닉네임 변경

저장된 하나의 계정 닉네임을 변경할 수 있습니다.

operation::update-nickName[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']

=== SNS 변경

저장된 하나의 계정 SNS 정보를 변경할 수 있습니다.

operation::update-sns[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']

=== 프로필 이미지 변경

저장된 하나의 계정 프로필 이미지를 변경할 수 있습니다.

operation::update-image[snippets='http-request,request-headers,request-parts,http-response,response-headers,response-fields']

=== 속성 중복 여부 확인

속성의 중복 여부를 확인할 수 있습니다. (중복 여부 확인 가능 속성: email, nickName)

operation::check-account[snippets='http-request,request-headers,request-parameters,http-response,response-headers,response-fields']