== 메뉴

=== 메뉴 생성

operation::create-menu[snippets='http-request,request-headers,request-parts,request-part-data-fields,http-response,response-headers,response-fields']

=== 메뉴 단건 조회
operation::menu-findOne[snippets='http-request,path-parameters,http-response,response-fields']

=== 메뉴 수정
operation::update-menu[snippets='http-request,request-headers,request-parts,request-part-data-fields,http-response']

=== 메뉴 삭제
operation::delete-menu[snippets='http-request,path-parameters,http-response']

=== 자기 메뉴 검색
operation::search-my-menu[snippets='http-request,request-parameters,http-response,response-headers,response-fields']

=== 특정 사용자가 생성한 메뉴 검색
operation::search-other-menu[snippets='http-request,request-parameters,http-response,response-headers,response-fields']

=== 특정 사용자가 좋아요한 메뉴 검색
operation::search-like-menu[snippets='http-request,request-parameters,http-response,response-headers,response-fields']

=== 전체 메뉴 검색
operation::search-menu[snippets='http-request,request-parameters,http-response,response-headers,response-fields']